apiVersion: apps/v1
kind: Deployment
metadata:
  name: openlog-be-deployment
  labels:
    app: openlog-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openlog-be
  template:
    metadata:
      labels:
        app: openlog-be
    spec:
      containers:
        - name: webapp
          image: danilocadeddu/openlog:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: openlog-be
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
